#!/usr/bin/env python
# coding: utf-8

# In[29]:


import pandas as pd
#数据加载
data = pd.read_csv(r'C:\Users\lishaowen\OneDrive - 上汽大众汽车有限公司\黑马\L4\Market_Basket_Optimisation.csv', header = None)
#print(data)
print(data.shape)

#遍历,万物transactions
transactions=[]
for i in range(0,data.shape[0]):
    temp=[]
    for j in range(0,data.shape[1]):
        if str(data.values[i,j])!= 'nan':
            temp.append(data.values[i,j])
    transactions.append(temp)

#频繁项集和关联规则
from efficient_apriori import apriori
itemsets, rules = apriori(transactions, min_support=0.02,  min_confidence=0.3)
print("频繁项集：", itemsets)
print("关联规则：", rules)


# In[ ]:




